services:
  postgres:
    image: postgres:latest
    container_name: postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: IVxijz7Zvob3
      POSTGRES_USER: postgres
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    networks:
      - shortening_links_nw
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_PASSWORD: IVxijz7Zvob3
      PGADMIN_DEFAULT_EMAIL: kiruhahaj9@gmail.com
    ports:
      - "8001:80"
    networks:
      - shortening_links_nw  

volumes:
  postgres:
  pgadmin_data:

networks:
  shortening_links_nw:
    driver: bridge