services:
  postgres:
    image: postgres:latest
    container_name: postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: IVxijz7Zvob3
      POSTGRES_USER: postgres
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    networks:
      - shortening_links_nw
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 3s
      timeout: 5s
      retries: 5
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_PASSWORD: IVxijz7Zvob3
      PGADMIN_DEFAULT_EMAIL: kiruhahaj9@gmail.com
    ports:
      - "8002:80"
    networks:
      - shortening_links_nw  
  redis:
    image: redis:latest
    container_name: redis
    volumes:
      - redis:/data
    ports:
      - "6379:6379"
    networks:
      - shortening_links_nw
  app:
    build:
      dockerfile: ./Dockerfile
      context: .
    container_name: app
    volumes:
      - .:/app
    environment:
      - DB_USER=postgres
      - DB_PASSWORD=IVxijz7Zvob3
      - DB_HOST=postgres
      - DB_PORT=5432
      - DATABASE=mydatabase
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DATABASE=0
    ports:
      - '8001:8000'
    networks:
      - shortening_links_nw
    depends_on:
      postgres:
        condition: service_healthy

volumes: 
  postgres:
  pgadmin_data:
  redis:

networks:
  shortening_links_nw:
    driver: bridge